version: '3'

# Set up all services
services:
  # First the AspNet Core app
  web:
    ## Get the image to use and set the container name
    image: api:latest
    container_name: api

    # State a dependancy on Redis working
    depends_on:
      - "redis_image"

    # Location of the Dockerfile
    build:
      context: .
      dockerfile: Dockerfile

    # Set access ports for localhost on the left
    ports:
      - "1234:80"

    # Configure a link to Redis
    links:
      - "redis_image"

  # The Redis Service, this label is required for the "Links" and Connection string
  redis_image:
    # Pull the image from Docker Hub
    image: redis

    # Give the container a name (any name you want)
    container_name: redis.cache

    # Port  Redis
    ports:
      - "6379:6379"